# Numpy Notes
> 参考[PythonDataScienceHandbook](https://github.com/nkjadhav/PythonDataScienceHandbook)

## numpy.ndarray对象

In [3]:
import numpy as np
X=np.arange(12).reshape(3,4)
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
print(X.ndim)
print(X.shape)
print(X.dtype)
print(X.size)
print(X.itemsize)

2
(3, 4)
int64
12
8


## numpy.ndarray的创建

In [7]:
print(np.zeros((2,2)))
print(np.ones((2,3),dtype=float))
print(np.full((2,4),fill_value=6))
print(np.arange(0,10,2))
print(np.linspace(0,1,5))
print(np.random.random((3,3)))
print(np.random.randint(0,12,(3,4)))
print(np.eye(4))

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6 6]
 [6 6 6 6]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.19051815 0.44845252 0.81181921]
 [0.54274865 0.95981341 0.12763539]
 [0.42606326 0.97861676 0.04447579]]
[[ 1  6 11  8]
 [ 7  2  8  7]
 [ 1  6  7  5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 访问元素

### 访问单一元素

In [8]:
X=np.arange(12).reshape(3,4)
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
print(X[0])    #对于该二维数组，其元素可看作3个一维数组

[0 1 2 3]


In [10]:
print(X[0][0])    #先访问一维数组，再访问一维数组的元素，类似C中的写法

0


In [12]:
print(X[0,-1])

3


### 切片
操作和Python的list几乎一致

In [13]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
print(X[0:2])

[[0 1 2 3]
 [4 5 6 7]]


In [15]:
print(X[0:2,:-1])

[[0 1 2]
 [4 5 6]]


In [16]:
print(X[:,::-1])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


### 布尔索引

In [17]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
print(X[X<5])

[0 1 2 3 4]


In [19]:
print(X[(X>3)&(X<10)])

[4 5 6 7 8 9]


### Fancy索引

In [20]:
print(X[[2,1]])

[[ 8  9 10 11]
 [ 4  5  6  7]]


In [23]:
print(X[1,[1,0]])

[5 4]


In [24]:
print(X[[1,2],[0,0]])

[4 8]


以上索引方式可互相组合

## 数组的拆分和组合

### 组合

In [28]:
x=np.array([1,2,3])
y=np.array([3,2,1])
print(np.concatenate([x,y]))

[1 2 3 3 2 1]


In [29]:
grid=np.array([[1,2,3],[4,5,6]])
print(np.concatenate([grid,grid]))
print(np.concatenate([grid,grid],axis=1))    #0为在列上拼接，1为在行上拼接

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


### 拆分

In [30]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


## 通函数

In [31]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
print(X+1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
print(X**2)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [35]:
print(X-100)

[[-100  -99  -98  -97]
 [ -96  -95  -94  -93]
 [ -92  -91  -90  -89]]


## 聚合函数

In [36]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
print(X.sum())

66


In [38]:
print(X.mean())

5.5


In [40]:
print(X.max())

11


In [41]:
print(X.min(axis=0))

[0 1 2 3]


In [42]:
print(X.max(axis=1))

[ 3  7 11]


## 排序

In [46]:
X=np.random.randint(0,11,size=(3,4))
print(X)

[[10  3  7  7]
 [ 3  4  7  0]
 [ 3  5  0  0]]


In [47]:
print(np.sort(X))

[[ 3  7  7 10]
 [ 0  3  4  7]
 [ 0  0  3  5]]


In [49]:
print(np.sort(X,axis=1))

[[ 3  7  7 10]
 [ 0  3  4  7]
 [ 0  0  3  5]]


In [50]:
print(np.sort(X,axis=0))

[[ 3  3  0  0]
 [ 3  4  7  0]
 [10  5  7  7]]


In [51]:
print(np.argsort(X))

[[1 2 3 0]
 [3 0 1 2]
 [2 3 0 1]]


## Broadcasting广播操作

广播发生在shape不同的数组进行通函数运算等操作时，遵循如下规则：
* 规则一：如果两个数组维度不同，那么维度更小的那个数组在其最左边添一维；例如一个是(3,3)，一个是(3,)，则第二个数组维度变为(1,3)
* 规则二：如果两个数组维度数相等，但不匹配，如果不匹配的维度中有1，则使其匹配；例如(3,3)和(1,3)，则第二个数组维度变为(3,3)
* 规则三：如果不匹配的数组在任何维度上都没有1存在了，就无法匹配，说明两数组无法进行广播操作

In [43]:
a=np.ones((2, 3))
b=np.arange(3)
print("a.shape:",a.shape,"\nb.shape:",b.shape)

a.shape: (2, 3) 
b.shape: (3,)


## 遍历

In [52]:
print(X)

[[10  3  7  7]
 [ 3  4  7  0]
 [ 3  5  0  0]]


In [54]:
for i in np.nditer(X):    #生成数组的迭代器，可通过参数使可通过迭代器修改原数组
    print(i,end=", ")

10, 3, 7, 7, 3, 4, 7, 0, 3, 5, 0, 0, 

In [61]:
for i in X.flat:   
    print(i,end=", ")

10, 3, 7, 7, 3, 4, 7, 0, 3, 5, 0, 0, 

In [59]:
for i in X.flatten():
    print(i,end=", ")

10, 3, 7, 7, 3, 4, 7, 0, 3, 5, 0, 0, 

不需要通过迭代来修改ndarray的元素，使用通函数效率更高